services:
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    restart: unless-stopped
    depends_on:
      - seq
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    ports:
      - "12201:12201/udp"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      - seq-input-gelf
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong@Passw0rd", "-Q", "SELECT 1", "-C"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
    volumes:
      - sqlserver-data:/var/opt/mssql
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "{{.Name}}"

volumes:
  seq-data:
  sqlserver-data:
